apiVersion: v1
kind: Service
metadata:
  name: web10service
spec:
  type: LoadBalancer
  selector:
    abra: dabra
  ports:
  - port: 8080
    targetPort: 80
    
---

apiVersion: v1
kind: Pod
metadata:
  name: webapplication10
  labels:
    abra: dabra
spec:
  containers:
  - name: webapp10container
    image: "mondayacr.azurecr.io/webapplication10:latest"
    ports:
    - containerPort: 80
      protocol: TCP
      name: http
